"""artist, album, track, genre and album_genres tables

Revision ID: 03ec4d09dc4a
Revises: 
Create Date: 2026-08-31 10:14:26.998129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03ec4d09dc4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=False),
    sa.Column('year_of_founding', sa.SmallInteger(), nullable=True),
    sa.Column('notes', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artist_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_artist_year_of_founding'), ['year_of_founding'], unique=False)

    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_genre_name'), ['name'], unique=True)

    op.create_table('album',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discogs_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=True),
    sa.Column('format', sa.Enum('vinyl', 'cd', 'digital', name='album_format'), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('cover_path', sa.String(length=128), nullable=False),
    sa.Column('notes', sa.String(length=256), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discogs_id')
    )
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_album_artist_id'), ['artist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_album_title'), ['title'], unique=False)

    op.create_table('album_genres',
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.PrimaryKeyConstraint('album_id', 'genre_id')
    )
    op.create_table('track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('track_number', sa.SmallInteger(), nullable=False),
    sa.Column('duration_seconds', sa.SmallInteger(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_track_album_id'), ['album_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_track_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_track_title'))
        batch_op.drop_index(batch_op.f('ix_track_album_id'))

    op.drop_table('track')
    op.drop_table('album_genres')
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_album_title'))
        batch_op.drop_index(batch_op.f('ix_album_artist_id'))

    op.drop_table('album')
    with op.batch_alter_table('genre', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_genre_name'))

    op.drop_table('genre')
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artist_year_of_founding'))
        batch_op.drop_index(batch_op.f('ix_artist_name'))

    op.drop_table('artist')
    # ### end Alembic commands ###
