"""removed discgos_api column from artist

Revision ID: 138f91bf4a66
Revises: 4a0a6c687265
Create Date: 2026-09-15 14:31:47.807249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '138f91bf4a66'
down_revision = '4a0a6c687265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_artist_discogs_id'), type_='unique')
        batch_op.drop_column('discogs_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discogs_id', sa.INTEGER(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_artist_discogs_id'), ['discogs_id'])

    # ### end Alembic commands ###
