"""changed artist cover_path and notes to optional

Revision ID: 28d28d20e70f
Revises: 9d91c59e4ee7
Create Date: 2026-09-08 11:37:28.621087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28d28d20e70f'
down_revision = '9d91c59e4ee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.alter_column('cover_path',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
        batch_op.alter_column('notes',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.alter_column('notes',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.alter_column('cover_path',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    # ### end Alembic commands ###
