"""
added discogs_id column to artist

Revision ID: 4a0a6c687265
Revises: 660ef9f51b0e
Create Date: 2026-09-15 14:02:00.046270

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "4a0a6c687265"
down_revision = "660ef9f51b0e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("artist", schema=None) as batch_op:
        batch_op.add_column(sa.Column("discogs_id", sa.Integer(), nullable=True))
        batch_op.create_unique_constraint("uq_artist_discogs_id", ["discogs_id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("artist", schema=None) as batch_op:
        batch_op.drop_constraint("uq_artist_discogs_id", type_="unique")
        batch_op.drop_column("discogs_id")

    # ### end Alembic commands ###
