"""changed album label to optional

Revision ID: 660ef9f51b0e
Revises: 28d28d20e70f
Create Date: 2026-09-08 11:40:12.017682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '660ef9f51b0e'
down_revision = '28d28d20e70f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.alter_column('label',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('album', schema=None) as batch_op:
        batch_op.alter_column('label',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###
